---
title: More About Exceptions
date: 2019-11-22
description:
  Working with and throwing exceptions.
spelling_exceptions:
  - blockchain
  - Geez
  - SHA
  - Hashcash
  - rethrow
  - Rethrowing
youtube: https://youtu.be/mLQlyYSvCEw
---
:imagesdir: /learn/images

[[axHCLhKQxzhwFHeqGvpZhWUIqRTRCEyt]]
== !

[.janini.jdk.compiler.smaller]
--
++++
<div class="message">More About Exceptions</div>
++++
....
public class Example {
  public static void main(String[] unused) {
    try {
      throw new Exception("More About Exceptions");
    } catch (Exception e) {
      System.out.println(e);
    }
  }
}
....
--

[[YVOVNHgIXQcGbotRhnTLjlRxlloFSLng]]
== Review: Types of Exceptions

[.lead]
//
Java exceptions are broken into three distinct categories:

[.s]
//
* *Checked exceptions*: these are for places where you _know_ something might go
wrong and it's out of your control
//
* *Unchecked exceptions* (or runtime errors): these are unanticipated errors
usually caused by something dumb that you (the programmer) did wrong
//
* *Errors*: these are reserved for serious system problems that are probably not
recoverable

[[ajpSqxeufhVlXQkgrigFcjuJqXwzCANS]]
== Exception Handling Strategies

[.lead]
//
Here are reasonable strategies for handling each kind of exception:

[.s]
//
* *Errors*: _don't_ try to handle these, just go bye-bye
//
* *Unchecked exceptions*: try to _avoid_ these by improving your code
//
* *Checked exceptions*: try to handle these and have your program
continue running, or exit gracefully...
//
* but don't go on unless you can.

[[RoxnUIFqZCBrBZnusOrpzbLuksmJMpdG]]
== Working with Exceptions

[.lead]
//
Java exceptions are just another kind of Java object&mdash;and they have some
useful features, particularly when debugging:

[.s]
//
* `toString`: like every other Java `Object`, exceptions can be printed
//
* `getMessage`: retrieves just the message associated with this exception
//
* `printStackTrace`: print a _stack trace_ for the error showing what caused it
and what other functions were involved

[[wIAiKctczCEQFknYPSiRbruXLqBIGBMy]]
== !Throwable Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html"></iframe>
</div>
++++

[[zzlPSnhuaDjSgoGIAkpIjUQZeiuerNQe]]
== !Working with Exceptions Examples

[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....

[[CTsKSqiFCfFyikLMwtUmDbmSXijFayAL]]
== Rethrowing Exceptions

[.lead]
//
Sometimes you may want to just record what happened but not know what to do with
an error.

In that case you may want to rethrow it out of the catch block:

[source,role='smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    // Log that something went wrong
    Log.e(TAG, input + " is not a valid URI");
    // Rethrow the exception
    throw(e);
  }
}
----

[[diIiwLksuhFzuaiuxOuRIZnfIpgBPFnP]]
== Throwing Your Own Exceptions

[.lead]
//
So how do we handle a case like this?

[source,java]
----
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
----

[[tZEORkretvixoGRTiPQxDkXOhkrgdAUE]]
== ! Throwing Your Own Exceptions

[.janini.smaller.compiler]
....
public class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
public class Example {
  public static void main(final String[] unused) {
    StringStorage stringStorage = new StringStorage(-1);
  }
}
....

[[TyzTkvyjvmKDPkZwmxwufvXMjajIlrHV]]
== `throw`

[.lead]
//
To throw an exception in Java we use the `throw` keyword:

[source,java]
----
Exception e = new Exception("you did something awful");
throw(e);
----

[[qoTmuDmRuBRgiUxPONZaOVhCRmlElcLw]]
== `throw` Well

[.lead]
//
If you need to throw an exception:

[.s]
//
* Look for an existing `Exception` class that's a good fit
//
* Or, create your own:

[source,java,role='s smaller']
----
public class MyException extends Exception {
}
throw(new MyException("bad bad"));
----

[[SRZEFPcrGpKfBdzGREcjDZALhTbKaIsC]]
== `finally`

[.lead]
//
Java's `try-catch` also supports a `finally` block. It is _always_ executed after
_either_ the `try` or the `catch` completes:

[source,java,role='smaller']
----
try {
  System.out.println("start");
  couldError();
  System.out.println("done");
} catch (Exception e) {
  System.out.println("catch");
} finally {
  System.out.println("finally");
}
----

[[mhmYjmPPucLHcPEFfhzCtQfFbnqfuYjZ]]
== ! `finally` Example

[.janini.smaller]
....
import java.util.Random;

static void couldError() {
  Random random = new Random();
  if (random.nextBoolean()) {
    Object it = null;
    it.hashCode();
  }
}

try {
  System.out.println("start");
  couldError();
  System.out.println("done");
} catch (Exception e) {
  System.out.println("catch");
} finally {
  System.out.println("finally");
}
....

[[eZOQBRhCvuQhjkIrABjfwolqygMADAfE]]
== Intelligent `try` Usage

[.lead]
//
You can make intelligent use of `try-catch` blocks to avoid repetitive sanity
checking:

[source,java,role='smaller']
----
JsonParser parser = new JsonParser();
JsonObject info = parser.parse(json).getAsJsonObject();
if (!info.has("metadata")) {
  return 0;
}
JsonObject metadata = info.getAsJsonObject("metadata");
if (!metadata.has("width")) {
  return 0;
}
JsonElement width = metadata.getAsJsonElement("width");
return width.getAsInt();
----

[[PTcgGbrBNJAzQGjhIpXKlPnMXeUoxUmP]]
== Intelligent `try` Usage

[.lead]
//
You can make intelligent use of `try-catch` blocks to avoid repetitive sanity
checking:

(This is particularly nice when you can chain calls together.)

[source,java,role='smaller']
----
try {
  JsonParser parser = new JsonParser();
  return parser.parse(json)
    .getAsJsonObject()
    .getAsJsonObject("metadata")
    .get("width")
    .getAsInt();
} catch (Exception e) {
  return 0;
}
----

[[wPTGIacnajnLigKsnSOrFdDtdgnMXQbn]]
[.oneword]
//
== Questions About Exceptions?

[[oApTeMfnuZvIlKHitawrVCWwZsdsdjoD]]
== Announcements

* No office hours today&mdash;they'll resume after break.
//
* Today's homework problem is not due until the _Monday_ after break.
//
* The link:/MP/5/[final project description] has been posted. Please get
started!
//
* Have a great break!

// vim: ts=2:sw=2:et
